# -------------------------------
# Enable debug
# -------------------------------
debug=true

# -------------------------------
# Application Info
# -------------------------------
spring.application.name=SmartContactManager

# -------------------------------
# Server Configuration
# -------------------------------
server.port=${PORT:8080}  

# -------------------------------
# Database Configuration
# -------------------------------
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=RgTktJHfLgZKspHyjXoLnOlJkaCilOGW
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
<<<<<<< HEAD:src/main/resources/static/image/application-prod.properties
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
=======
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
>>>>>>> 2e20c0aff63212736e3e82baade863f812afd1e2:src/main/resources/application-prod.properties

# -------------------------------
# File Upload Limits
# -------------------------------
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# -------------------------------
# Mail Configuration
# -------------------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true
